module.exports = [
    "O mel é o único alimento que não apodrece. Foram encontrados potes de mel no Egito com mais de 3.000 anos ainda comestíveis.",
    "O coração de uma baleia azul é tão grande que um ser humano poderia nadar através de suas artérias.",
    "As vacas têm melhores amigos e ficam estressadas quando são separadas deles.",
    "A França foi o último país a usar a guilhotina, em 1977, mesmo ano em que o primeiro filme de Star Wars foi lançado.",
    "O Monte Everest cresce cerca de 4 milímetros todos os anos devido ao movimento das placas tectônicas.",
    "Ratos dão risada quando sentem cócegas, mas o som é em uma frequência que humanos não ouvem.",
    "O Japão tem uma ilha cheia de coelhos selvagens chamada Okunoshima.",
    "A Rússia tem uma área de superfície maior do que a de Plutão.",
    "Cerca de 10% dos ossos de um gato estão na sua cauda.",
    "Os polvos têm três corações e o sangue deles é azul.",
    "As pegadas dos astronautas na Lua permanecerão lá por milhões de anos porque não há vento para apagá-las.",
    "Um raio é cinco vezes mais quente do que a superfície do Sol.",
    "O isqueiro foi inventado antes do fósforo.",
    "Bananas são bagas, mas morangos não são.",
    "É impossível bocejar e manter os olhos abertos ao mesmo tempo.",
    "O hino nacional da Espanha não possui letra.",
    "As formigas não dormem e não possuem pulmões.",
    "O alfabeto havaiano tem apenas 12 letras.",
    "Uma pessoa passa, em média, seis meses da vida esperando o semáforo ficar verde.",
    "O olho de um avestruz é maior do que o seu cérebro.",
    "Os pinguins podem saltar até 2 metros de altura fora da água.",
    "O tubarão-da-Groenlândia pode viver por mais de 400 anos.",
    "Se você baralhar um baralho de cartas corretamente, é provável que essa ordem exata nunca tenha existido antes na história.",
    "O som não se propaga no vácuo do espaço.",
    "A cada minuto, o corpo humano perde cerca de 30.000 a 40.000 células mortas da pele.",
    "A língua de uma girafa é tão longa que ela consegue limpar os próprios ouvidos com ela.",
    "Escorpiões brilham sob luz ultravioleta.",
    "A Grande Muralha da China não é visível a olho nu do espaço.",
    "O estômago humano produz uma nova camada de muco a cada duas semanas para não se digerir.",
    "As lontras do mar dão as mãos enquanto dormem para não se separarem pela correnteza.",
    "Plutão ainda não completou uma volta inteira ao redor do Sol desde que foi descoberto em 1930.",
    "O Google se chamava originalmente 'Backrub'.",
    "Existem mais árvores na Terra do que estrelas na Via Láctea.",
    "A Nutella foi inventada durante a 2ª Guerra Mundial por causa da escassez de cacau.",
    "Um caracol pode dormir por até três anos.",
    "O nariz e as orelhas nunca param de crescer ao longo da vida.",
    "O suor do hipopótamo é vermelho, funcionando como protetor solar.",
    "As zebras são brancas com listras pretas, e não o contrário.",
    "O melro consegue imitar o som de alarmes de carros.",
    "A Antártida é o maior deserto do mundo.",
    "Existem mais flamingos de plástico no mundo do que flamingos reais.",
    "Um dia em Vênus é mais longo do que um ano em Vênus.",
    "O DNA humano é 50% idêntico ao de uma banana.",
    "As impressões digitais de coalas são tão parecidas com as humanas que podem confundir cenas de crime.",
    "A Torre Eiffel cresce até 15 centímetros no verão devido à expansão térmica do ferro.",
    "O 'j' é a única letra que não aparece na Tabela Periódica.",
    "O tubarão é o único peixe que consegue piscar com os dois olhos.",
    "Ketchup já foi vendido como remédio para diarreia nos anos 1830.",
    "A Barbie tem um nome completo: Barbara Millicent Roberts.",
    "O Mickey Mouse foi o primeiro personagem de desenho animado a ganhar uma estrela na Calçada da Fama.",
    "Um lápis inteiro pode escrever cerca de 45.000 palavras.",
    "As abelhas podem reconhecer rostos humanos.",
    "O cérebro consome cerca de 20% de toda a energia do seu corpo.",
    "A água sanitária tem data de validade; ela perde a eficácia após seis meses.",
    "Os golfinhos dão nomes uns aos outros através de assobios específicos.",
    "A rainha Elizabeth II era uma mecânica treinada durante a 2ª Guerra Mundial.",
    "O primeiro despertador só tocava às 4 da manhã.",
    "A pipoca existe há mais de 6.000 anos.",
    "O ouro é comestível, desde que seja puro (24 quilates).",
    "Cada segundo, o Sol converte 4 milhões de toneladas de matéria em energia.",
    "O fogo não projeta sombra.",
    "Os ursos polares têm pele preta sob os pelos brancos.",
    "A Suíça é o país onde se consome mais chocolate no mundo.",
    "O primeiro computador pesava 27 toneladas.",
    "As borboletas sentem o gosto das coisas com os pés.",
    "Os cães não enxergam apenas em preto e branco; eles veem tons de azul e amarelo.",
    "Uma nuvem média pesa cerca de 500 toneladas.",
    "O café é a segunda mercadoria mais comercializada no mundo, perdendo apenas para o petróleo.",
    "Existem mais de 7.500 variedades de maçãs no mundo.",
    "A maior parte da poeira da sua casa é composta por pele morta.",
    "O coração humano bate mais de 100.000 vezes por dia.",
    "O nome oficial da cidade de Bangkok é o mais longo do mundo.",
    "Os cavalos-marinhos são monogâmicos e viajam de mãos dadas (caudas dadas).",
    "O cérebro humano é o objeto mais complexo do universo conhecido.",
    "O vidro é, tecnicamente, um líquido de alta viscosidade, não um sólido.",
    "Se você tentar impedir um espirro, pode romper um vaso sanguíneo na cabeça.",
    "A letra 'E' é a mais comum na língua inglesa e portuguesa.",
    "Os camelos podem beber 100 litros de água em apenas 10 minutos.",
    "A luz do Sol leva 8 minutos e 20 segundos para chegar à Terra.",
    "O deserto do Saara já foi uma floresta tropical.",
    "A maior árvore do mundo é uma sequoia chamada General Sherman.",
    "O rugido de um leão pode ser ouvido a 8 quilômetros de distância.",
    "As baleias cantam para se comunicar e seus hits podem durar meses.",
    "O primeiro vídeo do YouTube foi gravado em um zoológico.",
    "As baratas podem viver semanas sem cabeça.",
    "O corpo humano tem ferro suficiente para fazer um prego de 7 cm.",
    "A Lua se afasta da Terra cerca de 3,8 centímetros por ano.",
    "As unhas da mão dominante crescem mais rápido.",
    "O som de um estalo de dedos é o osso batendo na palma da mão.",
    "Um espirro viaja a cerca de 160 km/h.",
    "Os elefantes são os únicos animais que não conseguem pular.",
    "O bico do tucano é extremamente leve porque é feito de queratina esponjosa.",
    "A cidade de Roma foi a primeira a atingir 1 milhão de habitantes.",
    "O olho humano consegue distinguir 10 milhões de cores diferentes.",
    "As corujas não conseguem mover os olhos; elas giram a cabeça até 270 graus.",
    "O animal mais barulhento do oceano é o camarão-pistola.",
    "A borracha de apagar foi descoberta por acidente.",
    "As girafas não têm cordas vocais.",
    "A pipoca estoura porque a água dentro do grão vira vapor e expande.",
    "O soco de um camarão-louva-a-deus é tão rápido quanto uma bala de calibre 22.",
    "Um fato fascinante é que, como o espaço é um vácuo, não há atmosfera para propagar ondas sonoras, tornando-o um lugar absolutamente silencioso. Além disso, devido à imensa distância que a luz percorre, olhar para estrelas distantes é literalmente olhar para o passado, vendo-as como eram há milhares ou milhões de anos.",
    "Mesmo não sendo o mais próximo do Sol, Vênus é o planeta mais quente do Sistema Solar, com temperaturas médias de 450°C devido à sua densa atmosfera.",
    "Existem mais estrelas no universo observável do que todos os grãos de areia em todas as praias da Terra.",
    "Marte abriga o maior vulcão do Sistema Solar, o Olympus Mons, que é três vezes mais alto que o Monte Everest.",
    "A luz do Sol leva cerca de 8 minutos e 20 segundos para chegar à Terra.",
    // Adicione mais até completar 300 conforme necessário...
];
