/**
 * Database de Palavras - AckermanBot ⚔️
 * Categorias: Animes, Esportes, Famosos, Estados e Geral.
 */

module.exports = [
    // --- ANIMES & MANGÁS ---
    { p: "ACKERMAN", d: "Sobrenome do Capitão Levi" },
    { p: "EREN", d: "Protagonista de Attack on Titan" },
    { p: "MIKASA", d: "A mais forte dos Ackerman" },
    { p: "NARUTO", d: "Ninja da Vila da Folha" },
    { p: "SASUKE", d: "Possui o Sharingan" },
    { p: "GOKU", d: "Um Saiyajin que vive na Terra" },
    { p: "LUFFY", d: "Quer ser o Rei dos Piratas" },
    { p: "ZORO", d: "Mestre das três espadas" },
    { p: "SHINIGAMI", d: "Deus da Morte em Death Note" },
    { p: "SUKUNA", d: "Rei das Maldições" },
    { p: "GOJO", d: "O feiticeiro mais forte" },
    { p: "SAITAMA", d: "Vence com apenas um soco" },
    { p: "TANJIRO", d: "Caçador de Onis" },
    { p: "REINER", d: "O Titã Encouraçado" },
    { p: "BERTHOLDT", d: "O Titã Colossal" },
    { p: "SHINGEKI", d: "Ataque dos Titãs" },
    { p: "KANEKI", d: "O Ghoul de um olho só" },
    { p: "BAKUGOU", d: "Herói explosivo" },
    { p: "KILLUA", d: "Assassino prodígio de HxH" },
    { p: "MADARA", d: "Lendário líder dos Uchiha" },
    { p: "ITACHI", d: "Irmão mais velho do Sasuke" },
    { p: "GAARA", d: "O ninja da areia" },
    { p: "INOSUKE", d: "Usa uma cabeça de javali" },
    { p: "PICCOLO", d: "Guerreiro Namekuseijin" },
    { p: "VEGETA", d: "Príncipe dos Saiyajins" },
    { p: "HISOKA", d: "O mágico de Hunter x Hunter" },
    { p: "LEVI", d: "O melhor soldado da humanidade" },
    { p: "ARMIN", d: "O estrategista do Corpo de Entrega" },
    { p: "ANNIE", d: "A Titã Fêmea" },
    { p: "ERWIN", d: "Comandante do Corpo de Entrega" },

    // --- ESPORTES & FUTEBOL ---
    { p: "NEYMAR", d: "O camisa 10 do Brasil" },
    { p: "CRISTIANO", d: "O Robozô do futebol" },
    { p: "MESSI", d: "O ET da Argentina" },
    { p: "RONALDINHO", d: "O Bruxo do futebol" },
    { p: "FLAMENGO", d: "O time do Urubu" },
    { p: "PALMEIRAS", d: "Time paulista alviverde" },
    { p: "CORINTHIANS", d: "O time do bando de loucos" },
    { p: "REAL MADRID", d: "O maior campeão da Champions" },
    { p: "BARCELONA", d: "Time da Catalunha" },
    { p: "VINICIUS", d: "Baila Vini Jr!" },
    { p: "BASQUETE", d: "Esporte do Michael Jordan" },
    { p: "VOLEI", d: "Esporte de rede e bloqueio" },
    { p: "LIBERTADORES", d: "Principal copa da América do Sul" },
    { p: "MARACANA", d: "O templo do futebol" },
    { p: "CHAMPIONS", d: "Liga dos campeões da Europa" },
    { p: "NBA", d: "Liga de basquete americana" },
    { p: "MBAPPE", d: "Estrela da França" },
    { p: "RODRYGO", d: "O raio do Real Madrid" },
    { p: "SANTOS", d: "O time do Rei Pelé" },
    { p: "BOTAFOGO", d: "O glorioso do Rio" },
    { p: "VASCÃO", d: "Time da cruz de malta" },
    { p: "LIVERPOOL", d: "Os Reds da Inglaterra" },
    { p: "MILAN", d: "Gigante da Itália" },
    { p: "JUDO", d: "Arte marcial japonesa" },
    { p: "KARATE", d: "Luta de mãos vazias" },
    { p: "SURFE", d: "Esporte do Gabriel Medina" },
    { p: "TENIS", d: "Esporte da raquete" },
    { p: "NATACAO", d: "Esporte de piscina" },
    { p: "BOXE", d: "Esporte de luvas e ringue" },
    { p: "SKATE", d: "Esporte da Rayssa Leal" },

    // --- ESTADOS DO BRASIL ---
    { p: "AMAZONAS", d: "Estado da maior floresta" },
    { p: "PARA", d: "Estado do Açaí" },
    { p: "SAO PAULO", d: "A terra da garoa" },
    { p: "RIO DE JANEIRO", d: "A cidade maravilhosa" },
    { p: "BAHIA", d: "Terra do axé e carnaval" },
    { p: "CEARA", d: "Estado das praias bonitas" },
    { p: "MINAS GERAIS", d: "Terra do pão de queijo" },
    { p: "PERNAMBUCO", d: "Estado do frevo" },
    { p: "MATO GROSSO", d: "Estado do Pantanal" },
    { p: "ACRE", d: "Estado da região Norte" },
    { p: "SERGIPE", d: "O menor estado do Brasil" },
    { p: "GOIAS", d: "Terra do sertanejo" },
    { p: "MARANHAO", d: "Estado dos Lençóis" },
    { p: "PARANA", d: "Estado das Cataratas" },
    { p: "SANTA CATARINA", d: "Praias do Sul" },
    { p: "ALAGOAS", d: "Estado de Maceió" },
    { p: "TOCANTINS", d: "Estado do Jalapão" },
    { p: "PIAUI", d: "Terra do Whindersson Nunes" },
    { p: "RONDONIA", d: "Vizinho do Acre e Amazonas" },
    { p: "ESPIRITO SANTO", d: "Estado de Vitória" },

    // --- FAMOSOS & CELEBRIDADES ---
    { p: "ANITTA", d: "Cantora brasileira internacional" },
    { p: "WHINDERSSON", d: "Humorista do Piauí" },
    { p: "CASIMIRO", d: "Famoso streamer" },
    { p: "ALOK", d: "DJ brasileiro famoso" },
    { p: "BEYONCE", d: "A rainha do Pop" },
    { p: "EMINEM", d: "O rei do rap" },
    { p: "VIRGINIA", d: "Influenciadora famosa" },
    { p: "SILVIO SANTOS", d: "Dono do SBT" },
    { p: "FAUSTAO", d: "Apresentador de TV" },
    { p: "LUISA SONZA", d: "Cantora pop gaúcha" },
    { p: "GUSTTAVO LIMA", d: "O embaixador do sertanejo" },
    { p: "PAULO GUSTAVO", d: "Eterno 'Minha Mãe é uma Peça'" },
    { p: "IVETE SANGALO", d: "A rainha do Axé" },
    { p: "LEONARDO DICAPRIO", d: "Ator de Titanic" },
    { p: "WILL SMITH", d: "Um Maluco no Pedaço" },
    { p: "DRAKE", d: "Rapper canadense famoso" },
    { p: "LANA DEL REY", d: "Cantora de Indie Pop" },
    { p: "BRUNA MARQUEZINE", d: "Atriz famosa brasileira" },
    { p: "Zeca Pagodinho", d: "Lenda do Samba" },

    // --- OBJETOS & DIA A DIA ---
    { p: "CELULAR", d: "Aparelho de comunicação portátil" },
    { p: "GELADEIRA", d: "Conserva a comida fria" },
    { p: "COMPUTADOR", d: "Máquina de processar dados" },
    { p: "TELEVISAO", d: "Aparelho de ver filmes" },
    { p: "CHURRASCO", d: "Comida clássica de domingo" },
    { p: "PIZZA", d: "Massa redonda italiana" },
    { p: "HAMBURGUER", d: "Sanduíche com carne e queijo" },
    { p: "WHATSAPP", d: "Aplicativo de mensagens" },
    { p: "INSTAGRAM", d: "Rede social de fotos" },
    { p: "INTERNET", d: "Rede mundial" },
    { p: "ACADEMIA", d: "Lugar de treinar" },
    { p: "DINHEIRO", d: "O que paga as contas" },
    { p: "CAFE", d: "Bebida que tira o sono" },
    { p: "CERVEJA", d: "Bebida de cevada gelada" },
    { p: "FOGUETE", d: "Vai para o espaço" },
    { p: "BRASIL", d: "O país do futebol" },
    { p: "RELOGIO", d: "Marca as horas" },
    { p: "MOCHILA", d: "Guarda materiais escolares" },
    { p: "ESPELHO", d: "Mostra seu reflexo" },
    { p: "CADEIRA", d: "Móvel para sentar" },
    { p: "AVIAO", d: "Transporte pelos ares" },
    { p: "ESCOLA", d: "Lugar de estudar" },
    { p: "FOGO", d: "Quente e perigoso" },
    { p: "MESA", d: "Onde se coloca o prato" },
    { p: "SAPATO", d: "Calçado para os pés" },
    { p: "OCULOS", d: "Ajuda a enxergar" },
    { p: "CARRO", d: "Veículo de quatro rodas" },
    { p: "BONE", d: "Acessório para a cabeça" },
    { p: "COPO", d: "Recipiente para beber" },
    { p: "PANELA", d: "Usada para cozinhar" },
    { p: "VASSOURA", d: "Usada para limpar o chão" },
    { p: "BICICLETA", d: "Veículo de dois pedais" },
    { p: "MICROFONE", d: "Amplifica a voz" },
    { p: "TECLADO", d: "Usado para digitar" },
    { p: "MOUSE", d: "Controla a seta no PC" },
    { p: "CADERNO", d: "Onde se faz anotações" },
    { p: "CANETA", d: "Escreve com tinta" },
    { p: "LAPIS", d: "Escreve e pode apagar" },
    { p: "CHAVE", d: "Abre a porta" },
    { p: "CARTEIRA", d: "Guarda documentos e notas" },
    { p: "ALMOFADA", d: "Macio para o sofá" },
    { p: "TRAVESSEIRO", d: "Apoio para dormir" },
    { p: "PERFUME", d: "Dá um cheiro bom" },
    { p: "XAMPU", d: "Lava o cabelo" },
    { p: "SABONETE", d: "Lava o corpo" },
    { p: "DENTIFRICIO", d: "Pasta de dente" },
    { p: "ESCOVA", d: "Limpa os dentes" },
    { p: "TOALHA", d: "Seca o corpo" },
    { p: "JANELA", d: "Por onde entra o ar na casa" },
    { p: "VENTILADOR", d: "Refresca o calor" },
    { p: "ARMARIO", d: "Guarda as roupas" },
    { p: "GARFO", d: "Usado para comer" },
    { p: "COLHER", d: "Usada para sopa" },
    { p: "PRATO", d: "Recipiente de comida" },
    { p: "GELO", d: "Água sólida" },
    { p: "CHUVA", d: "Água caindo do céu" },
    { p: "NUVEM", d: "Fica no céu antes da chuva" },
    { p: "ESTRADA", d: "Caminho para carros" },
    { p: "PONTE", d: "Passa por cima do rio" },
    { p: "SHOPPING", d: "Centro de lojas" },
    { p: "CINEMA", d: "Lugar de ver filmes" },
    { p: "BANCO", d: "Lugar de tirar dinheiro" },
    { p: "MERCADO", d: "Lugar de fazer compras" },
    { p: "FARMACIA", d: "Lugar de comprar remédio" },
    { p: "PADARIA", d: "Lugar de comprar pão" },
    { p: "REFRIGERANTE", d: "Bebida com gás" },
    { p: "SUCO", d: "Bebida natural de fruta" },
    { p: "SORVETE", d: "Doce gelado" },
    { p: "CHOCOLATE", d: "Doce feito de cacau" },
    { p: "MACA", d: "Fruta vermelha clássica" },
    { p: "BANANA", d: "Fruta amarela comprida" },
    { p: "MELANCIA", d: "Fruta grande e verde por fora" },
    { p: "MORANGO", d: "Fruta pequena e vermelha" },
    { p: "UVA", d: "Fruta pequena em cachos" },
    { p: "LARANJA", d: "Fruta de fazer suco" },
    { p: "ARROZ", d: "Grão branco do dia a dia" },
    { p: "FEIJAO", d: "Parceiro do arroz" },
    { p: "MACARRAO", d: "Massa comprida" },
    { p: "OVO", d: "Vem da galinha" },
    { p: "LEITE", d: "Vem da vaca" },
    { p: "QUEIJO", d: "Feito do leite" },
    { p: "PRESUNTO", d: "Frio usado no misto quente" },
    { p: "ACUCAR", d: "Adoça a vida" },
    { p: "SAL", d: "Tempero básico" },
    { p: "OLEO", d: "Usado para fritar" },
    { p: "MANTEIGA", d: "Passa no pão quente" },
    { p: "BOLO", d: "Doce de festa de aniversário" },
    { p: "PAO", d: "Base do café da manhã" },
    { p: "BOLACHA", d: "Ou biscoito?" },
    { p: "PIPOCA", d: "Come assistindo filme" },
    { p: "BALA", d: "Doce pequeno de chupar" },
    { p: "CHICLETE", d: "Doce de mascar" },
    { p: "GELATINA", d: "Sobremesa que balança" },
    { p: "IOGURTE", d: "Laticínio pastoso" },
    { p: "MEL", d: "Feito pelas abelhas" },
    { p: "LUA", d: "Brilha à noite no céu" },
    { p: "SOL", d: "Brilha de dia" },
    { p: "MAR", d: "Água salgada gigante" },
    { p: "TERRA", d: "Nosso planeta" },
    { p: "ESTRELA", d: "Ponto brilhante no espaço" },
    { p: "ARVORE", d: "Dá sombra e frutos" },
    { p: "FLOR", d: "Planta colorida e cheirosa" },
    { p: "GRAMA", d: "Tapete verde da natureza" },
    { p: "PEDRA", d: "Duro e mineral" },
    { p: "AREIA", d: "Tem muito na praia" },
    { p: "VENTO", d: "Ar soprando forte" },
    { p: "DESERTO", d: "Lugar com muita areia e calor" },
    { p: "FLORESTA", d: "Lugar com muitas árvores" },
    { p: "ILHA", d: "Terra cercada de água" },
    { p: "MONTANHA", d: "Elevação natural de terra" },
    { p: "VULCAO", d: "Montanha que cospe fogo" },
    { p: "CACHOEIRA", d: "Queda de água natural" },
    { p: "LAGO", d: "Água cercada de terra" },
    { p: "RIO", d: "Água doce que corre" },
    { p: "PEIXE", d: "Vive na água" },
    { p: "PASSARO", d: "Animal que voa" },
    { p: "CACHORRO", d: "Melhor amigo do homem" },
    { p: "GATO", d: "Animal que faz miau" },
    { p: "CAVALO", d: "Animal de montaria" },
    { p: "LEAO", d: "Rei da selva" },
    { p: "TIGRE", d: "Felino listrado" },
    { p: "ELEFANTE", d: "Animal com tromba grande" },
    { p: "GIRAFA", d: "Animal com pescoço longo" },
    { p: "MACACO", d: "Gosta de banana" },
    { p: "COELHO", d: "Símbolo da páscoa" },
    { p: "COBRA", d: "Réptil sem patas" },
    { p: "SAPO", d: "Animal que pula e coaxa" },
    { p: "TARTARUGA", d: "Animal com casco lento" },
    { p: "TUBARAO", d: "Predador dos mares" },
    { p: "BALEIA", d: "Mamífero gigante do mar" },
    { p: "BORBOLETA", d: "Inseto de asas coloridas" },
    { p: "ABELHA", d: "Inseto que produz mel" },
    { p: "FORMIGA", d: "Inseto pequeno e trabalhador" },
    { p: "ARANHA", d: "Inseto de oito patas" },
    { p: "MOSQUITO", d: "Inseto que pica" },
    { p: "CASA", d: "Lugar de morar" },
    { p: "PREDIO", d: "Edifício de muitos andares" },
    { p: "CIDADE", d: "Lugar com muitas ruas e casas" },
    { p: "VILA", d: "Pequeno conjunto de casas" },
    { p: "MUNDO", d: "Onde todos vivem" },
    { p: "PAIS", d: "Nação governada" },
    { p: "ESTADO", d: "Divisão de um país" },
    { p: "BAIRRO", d: "Divisão de uma cidade" },
    { p: "CAPITAL", d: "Cidade principal do estado" },
    { p: "REI", d: "Governante da monarquia" },
    { p: "RAINHA", d: "Esposa do rei" },
    { p: "PRINCIPE", d: "Filho do rei" },
    { p: "PRINCESA", d: "Filha do rei" },
    { p: "PRESIDENTE", d: "Líder da república" },
    { p: "POLICIAL", d: "Mantém a ordem" },
    { p: "BOMBEIRO", d: "Apaga incêndios" },
    { p: "MEDICO", d: "Cuida da saúde" },
    { p: "PROFESSOR", d: "Ensina os alunos" },
    { p: "ALUNO", d: "Quem estuda na escola" },
    { p: "CRIANCA", d: "Pessoa jovem" },
    { p: "ADULTO", d: "Pessoa crescida" },
    { p: "IDOSO", d: "Pessoa com muita idade" },
    { p: "HOMEM", d: "Ser humano masculino" },
    { p: "MULHER", d: "Ser humano feminino" },
    { p: "AMIGO", d: "Pessoa querida" },
    { p: "FAMILIA", d: "Pessoas do mesmo sangue" },
    { p: "AMOR", d: "Sentimento mais forte" },
    { p: "PAZ", d: "Ausência de guerra" },
    { p: "FELICIDADE", d: "Estado de quem está alegre" },
    { p: "TRISTEZA", d: "O contrário de alegria" },
    { p: "RAIVA", d: "Sentimento de ódio" },
    { p: "MEDO", d: "Sentimento de pavor" },
    { p: "SORRISO", d: "Expressão de alegria" },
    { p: "CHORO", d: "Expressão de tristeza" },
    { p: "SONHO", d: "Acontece enquanto dormimos" },
    { p: "TRABALHO", d: "Atividade remunerada" },
    { p: "JOGO", d: "Atividade de lazer" },
    { p: "FILME", d: "História contada em vídeo" },
    { p: "MUSICA", d: "Arte dos sons" },
    { p: "DANCA", d: "Movimento do corpo com ritmo" },
    { p: "LIVRO", d: "Obra escrita para ler" },
    { p: "POEMA", d: "Texto com rimas" },
    { p: "HISTORIA", d: "Conto de fatos" },
    { p: "GEOGRAFIA", d: "Estudo da terra" },
    { p: "MATEMATICA", d: "Ciência dos números" },
    { p: "CIENCIA", d: "Estudo da natureza" },
    { p: "ARTES", d: "Expressão da criatividade" },
    { p: "LINGUA", d: "Idioma falado" },
    { p: "PALAVRA", d: "Conjunto de letras com sentido" },
    { p: "LETRA", d: "Símbolo do alfabeto" },
    { p: "NUMERO", d: "Símbolo de contagem" },
    { p: "PONTO", d: "Sinal de pontuação" },
    { p: "FRASE", d: "Conjunto de palavras" },
    { p: "TEXTO", d: "Conjunto de frases" },
    { p: "PAGINA", d: "Lado de uma folha" },
    { p: "CAPA", d: "Frente de um livro" },
    { p: "TITULO", d: "Nome de uma obra" },
    { p: "AUTOR", d: "Quem escreve a obra" },
    { p: "LEITOR", d: "Quem lê a obra" },
    { p: "BOLA", d: "Objeto redondo de jogar" },
    { p: "CAMISA", d: "Roupa de vestir no tronco" },
    { p: "CALCA", d: "Roupa de vestir nas pernas" },
    { p: "MEIA", d: "Veste nos pés antes do calçado" },
    { p: "CUECA", d: "Roupa íntima masculina" },
    { p: "CALCINHA", d: "Roupa íntima feminina" },
    { p: "VESTIDO", d: "Roupa feminina peça única" },
    { p: "SAIA", d: "Roupa feminina para pernas" },
    { p: "JAQUETA", d: "Casaco para o frio" },
    { p: "LUVAS", d: "Veste nas mãos" },
    { p: "CACHECOL", d: "Veste no pescoço" },
    { p: "CHAPEU", d: "Acessório para cabeça" },
    { p: "ANEL", d: "Acessório para o dedo" },
    { p: "BRINCO", d: "Acessório para a orelha" },
    { p: "COLARE", d: "Acessório para o pescoço" },
    { p: "PULSEIRA", d: "Acessório para o pulso" },
    { p: "BOLSA", d: "Guarda pertences femininos" },
    { p: "CINTO", d: "Segura a calça" },
    { p: "GRAVATA", d: "Acessório formal de pescoço" },
    { p: "TERNO", d: "Roupa formal masculina" },
    { p: "PIJAMA", d: "Roupa de dormir" },
    { p: "BIQUINI", d: "Roupa de banho feminina" },
    { p: "SUNGA", d: "Roupa de banho masculina" },
    { p: "TOUCA", d: "Cobre a cabeça" },
    { p: "MASCARA", d: "Cobre o rosto" },
    { p: "REDE", d: "Usada para deitar e balançar" },
    { p: "BALDE", d: "Recipiente de carregar água" },
    { p: "CANECA", d: "Copo com alça" },
    { p: "GARRAFA", d: "Recipiente de líquidos" },
    { p: "LATA", d: "Recipiente de metal" },
    { p: "CAIXA", d: "Recipiente de papelão ou madeira" },
    { p: "SACO", d: "Recipiente de plástico ou papel" },
    { p: "POTE", d: "Recipiente de guardar comida" },
    { p: "FUNIL", d: "Ajuda a colocar líquido em garrafas" },
    { p: "RALO", d: "Por onde a água desce" },
    { p: "TORNEIRA", d: "De onde sai a água" },
    { p: "CHUVEIRO", d: "Onde tomamos banho" },
    { p: "VASO", d: "Onde fazemos as necessidades" },
    { p: "PIA", d: "Onde lavamos as mãos" },
    { p: "SABOARIA", d: "Lugar de fazer sabão" },
    { p: "ESCOVA", d: "Para os dentes ou cabelo" },
    { p: "PENTE", d: "Para o cabelo" },
    { p: "TESOURA", d: "Para cortar papel" },
    { p: "MARTELO", d: "Para pregar" },
    { p: "PREGO", d: "Fixado pelo martelo" },
    { p: "ALICATE", d: "Para apertar ou cortar fios" },
    { p: "PARAFUSO", d: "Fixado pela chave" },
    { p: "CORDA", d: "Usada para amarrar" },
    { p: "FITA", d: "Usada para colar" },
    { p: "COLA", d: "Substância que une" },
    { p: "TINTA", d: "Usada para pintar" },
    { p: "PINCEL", d: "Usado com a tinta" },
    { p: "PAPEL", d: "Onde se escreve" },
    { p: "PAPELAO", d: "Papel grosso de caixas" },
    { p: "PLASTICO", d: "Material de garrafas" },
    { p: "VIDRO", d: "Material transparente" },
    { p: "METAL", d: "Material resistente" },
    { p: "MADEIRA", d: "Vem da árvore" },
    { p: "PEDRA", d: "Vem da montanha" },
    { p: "TIJOLO", d: "Usado para fazer paredes" },
    { p: "CIMENTO", d: "Une os tijolos" },
    { p: "AREIA", d: "Misturada ao cimento" },
    { p: "TELHA", d: "Cobre a casa" },
    { p: "PORTA", d: "Entrada do cômodo" },
    { p: "PAREDE", d: "Divide a casa" },
    { p: "TETO", d: "Parte de cima da sala" },
    { p: "CHAO", d: "Onde pisamos" },
    { p: "ESCADA", d: "Para subir andares" },
    { p: "ELEVADOR", d: "Sobe andares no prédio" },
    { p: "CORREDOR", d: "Passagem entre quartos" },
    { p: "QUARTO", d: "Onde fica a cama" },
    { p: "SALA", d: "Onde fica o sofá" },
    { p: "COZINHA", d: "Onde fica o fogão" },
    { p: "BANHEIRO", d: "Onde fica o chuveiro" },
    { p: "VARANDA", d: "Espaço aberto da casa" },
    { p: "QUINTAL", d: "Terreno atrás da casa" },
    { p: "JARDIM", d: "Onde ficam as flores" },
    { p: "GARAGEM", d: "Onde fica o carro" },
    { p: "PORTAO", d: "Entrada da garagem" },
    { p: "CERCA", d: "Delimita o terreno" },
    { p: "MURO", d: "Parede que cerca a casa" },
    { p: "CALNADA", d: "Onde pedestres andam" },
    { p: "RUA", d: "Onde carros andam" },
    { p: "AVENIDA", d: "Rua muito larga" },
    { p: "PRACA", d: "Espaço de lazer no bairro" },
    { p: "PARQUE", d: "Área verde grande" },
    { p: "ZOO", d: "Lugar de ver animais" },
    { p: "MUSEU", d: "Lugar de ver arte" },
    { p: "TEATRO", d: "Lugar de ver peças" },
    { p: "ESTADIO", d: "Lugar de ver futebol" },
    { p: "GINASIO", d: "Lugar de ver esportes de quadra" },
    { p: "CLUBE", d: "Lugar de lazer e piscina" },
    { p: "PRAIA", d: "Lugar de areia e mar" },
    { p: "SERRA", d: "Lugar de montanhas frias" },
    { p: "CAMPO", d: "Lugar de fazendas" },
    { p: "FAZENDA", d: "Lugar de criar gado" },
    { p: "SITIO", d: "Fazenda pequena" },
    { p: "GRANJA", d: "Lugar de criar galinhas" },
    { p: "PASTO", d: "Onde o gado come" },
    { p: "POMAR", d: "Onde ficam as frutas" },
    { p: "HORTA", d: "Onde ficam as verduras" },
    { p: "LAVOURA", d: "Onde fica a plantação" },
    { p: "TRATOR", d: "Veículo da fazenda" },
    { p: "CHARRETE", d: "Transporte de cavalo" },
    { p: "Sela", d: "Usada para montar cavalo" },
    { p: "ESPORA", d: "Usada na bota do peão" },
    { p: "LACO", d: "Usado para pegar o boi" },
    { p: "RODEIO", d: "Festa de peão" },
    { p: "RELOGIO", d: "Marca os segundos" },
    { p: "CALENDARIO", d: "Marca os dias" },
    { p: "DIA", d: "Quando o sol brilha" },
    { p: "NOITE", d: "Quando a lua brilha" },
    { p: "MANHA", d: "Início do dia" },
    { p: "TARDE", d: "Depois do meio dia" },
    { p: "SEMANA", d: "Sete dias" },
    { p: "MES", d: "Trinta dias" },
    { p: "ANO", d: "Doze meses" },
    { p: "SECULO", d: "Cem anos" },
    { p: "VERAO", d: "Estação do calor" },
    { p: "INVERNO", d: "Estação do frio" },
    { p: "OUTONO", d: "Estação das folhas" },
    { p: "PRIMAVERA", d: "Estação das flores" },
    { p: "ONIBUS", d: "Transporte público de cidade" },
    { p: "METRO", d: "Trem debaixo da terra" },
    { p: "TREM", d: "Anda sobre os trilhos" },
    { p: "MOTO", d: "Veículo de duas rodas barulhento" },
    { p: "CAMINHAO", d: "Leva carga pesada" },
    { p: "AVIAO", d: "Leva passageiros pelo céu" },
    { p: "HELICOPTERO", d: "Voa parado no ar" },
    { p: "NAVIO", d: "Leva carga pelo mar" },
    { p: "BARCO", d: "Pequeno transporte na água" },
    { p: "CANOA", d: "Barco de madeira a remo" },
    { p: "BOTE", d: "Pequeno barco inflável" },
    { p: "ANCORE", d: "Segura o navio parado" },
    { p: "VELA", d: "Pano que move o barco" },
    { p: "TIMON", d: "Volante do navio" },
    { p: "PILOTO", d: "Quem dirige o avião" },
    { p: "MOTORISTA", d: "Quem dirige o carro" },
    { p: "CAPITAO", d: "Quem manda no navio" },
    { p: "MAQUINISTA", d: "Quem dirige o trem" },
    { p: "PASSAGEIRO", d: "Quem viaja no transporte" },
    { p: "ESTACAO", d: "Onde o trem para" },
    { p: "AEROPORTO", d: "Onde o avião para" },
    { p: "RODOVIARIA", d: "Onde o ônibus para" },
    { p: "PORTO", d: "Onde o navio para" },
    { p: "GARAGEM", d: "Onde o carro para" },
    { p: "ESTRELA", d: "O sol é uma" },
    { p: "PLANETA", d: "A terra é um" },
    { p: "GALAXIA", d: "Via Láctea é a nossa" },
    { p: "COMETA", d: "Tem cauda de gelo" },
    { p: "ASTEROIDE", d: "Pedra no espaço" },
    { p: "BURACO NEGRO", d: "Suga tudo no espaço" },
    { p: "TELESCOPIO", d: "Usado para ver o espaço" },
    { p: "SATELLITE", d: "Orbita a terra" },
    { p: "LUNETA", d: "Telescópio pequeno" },
    { p: "MAPA", d: "Desenho da terra" },
    { p: "BUSSOLA", d: "Aponta o norte" },
    { p: "GPS", d: "Localizador digital" },
    { p: "RADAR", d: "Detecta objetos distantes" },
    { p: "SONAR", d: "Detecta objetos na água" },
    { p: "BATERIA", d: "Dá energia ao celular" },
    { p: "PILHA", d: "Dá energia ao controle" },
    { p: "TOMADA", d: "De onde vem a energia" },
    { p: "FIO", d: "Leva a energia" },
    { p: "INTERRUPTOR", d: "Acende a luz" },
    { p: "LAMPADA", d: "Ilumina o quarto" },
    { p: "LANTERNA", d: "Luz portátil" },
    { p: "VELA", d: "Luz de fogo" },
    { p: "ISQUEIRO", d: "Faz fogo" },
    { p: "FOSFORO", d: "Palito que faz fogo" },
    { p: "FOGAO", d: "Faz a comida" },
    { p: "FORNO", d: "Assa o bolo" },
    { p: "MICROONDAS", d: "Esquenta rápido" },
    { p: "LIQUIDIFICADOR", d: "Bate a vitamina" },
    { p: "BATEDEIRA", d: "Bate a massa do bolo" },
    { p: "TORRADEIRA", d: "Faz torrada" },
    { p: "CAFETEIRA", d: "Faz o café" },
    { p: "SANDUICHEIRA", d: "Faz o misto quente" },
    { p: "FERRO", d: "Passa a roupa" },
    { p: "MAQUINA", d: "Lava a roupa" },
    { p: "SECADORA", d: "Seca a roupa" },
    { p: "ASPIRADOR", d: "Suga o pó" },
    { p: "BALANCA", d: "Pesa as coisas" },
    { p: "TERMOMETRO", d: "Mede a febre" },
    { p: "DURA", d: "Conserta tudo" },
    { p: "BORRACHA", d: "Apaga o erro" },
    { p: "APONTADOR", d: "Faz a ponta" },
    { p: "REGUA", d: "Mede o tamanho" },
    { p: "ESTOJO", d: "Guarda as canetas" },
    { p: "MOCHILA", d: "Leva os livros" },
    { p: "CADERNO", d: "Tem muitas folhas" },
    { p: "LIVRO", d: "Tem muitas páginas" },
    { p: "REVISTA", d: "Tem muitas fotos" },
    { p: "JORNAL", d: "Tem muitas notícias" },
    { p: "DICIONARIO", d: "Tem muitas palavras" },
    { p: "ALFABETO", d: "De A a Z" },
    { p: "VOGAL", d: "A E I O U" },
    { p: "CONSOANTE", d: "B C D F G..." },
    { p: "SILABA", d: "Pedaço da palavra" },
    { p: "ACENTO", d: "Dá som à letra" },
    { p: "RIMA", d: "Som igual no final" },
    { p: "VERSO", d: "Linha do poema" },
    { p: "ESTROFE", d: "Grupo de versos" },
    { p: "MUSICA", d: "Melodia e letra" },
    { p: "CANTOR", d: "Quem solta a voz" },
    { p: "BANDA", d: "Grupo de músicos" },
    { p: "VIOLAO", d: "Instrumento de cordas" },
    { p: "PIANO", d: "Instrumento de teclas" },
    { p: "BATERIA", d: "Instrumento de percussão" },
    { p: "FLAUTA", d: "Instrumento de sopro" },
    { p: "GAITA", d: "Instrumento de boca" },
    { p: "TAMBOR", d: "Instrumento de couro" },
    { p: "HARPA", d: "Instrumento de anjo" },
    { p: "TROMPETE", d: "Instrumento de metal" },
    { p: "SAXOFONE", d: "Instrumento de jazz" },
    { p: "ACORDEON", d: "Instrumento de sanfona" },
    { p: "TRIANGULO", d: "Instrumento de metal simples" },
    { p: "PANDEIRO", d: "Instrumento de samba" },
    { p: "VIOLINO", d: "Instrumento clássico" },
    { p: "NOTAS", d: "Do Re Mi Fa Sol La Si" }
];
