module.exports = [
    // --- FÁCEIS (CLÁSSICOS & POPULARES) ---
    { nome: "Levi Ackerman", dificuldade: "Fácil", dicas: ["É o soldado mais forte da humanidade.", "Tem obsessão por limpeza.", "Usa o DMT com maestria."] },
    { nome: "Naruto Uzumaki", dificuldade: "Fácil", dicas: ["Possui uma raposa de nove caudas selada.", "Seu prato favorito é o Ichiraku Ramen.", "Diz constantemente 'Dattebayo'."] },
    { nome: "Monkey D. Luffy", dificuldade: "Fácil", dicas: ["Seu corpo é feito de borracha.", "Deseja ser o Rei dos Piratas.", "Usa um chapéu de palha icônico."] },
    { nome: "Goku", dificuldade: "Fácil", dicas: ["É um Saiyajin criado na Terra.", "Sua técnica principal é o Kamehameha.", "Busca sempre as Esferas do Dragão."] },
    { nome: "Saitama", dificuldade: "Fácil", dicas: ["Derrota qualquer um com apenas um soco.", "Ficou careca de tanto treinar.", "É um herói por hobby."] },
    { nome: "Pikachu", dificuldade: "Fácil", dicas: ["É o mascote mais famoso da franquia Pokémon.", "Armazena eletricidade em suas bochechas.", "Diz apenas o próprio nome."] },
    { nome: "Tanjiro Kamado", dificuldade: "Fácil", dicas: ["Carrega sua irmã em uma caixa.", "Usa a Respiração da Água.", "Tem uma cicatriz na testa."] },
    { nome: "Satoru Gojo", dificuldade: "Fácil", dicas: ["É o feiticeiro Jujutsu mais forte.", "Usa uma venda nos olhos.", "Possui a técnica do Infinito."] },
    { nome: "Eren Yeager", dificuldade: "Fácil", dicas: ["Possui o Titã de Ataque.", "Jurou exterminar todos os titãs.", "Ativou o Rugido da Terra."] },
    { nome: "Vegeta", dificuldade: "Fácil", dicas: ["É o Príncipe dos Saiyajins.", "Seu maior rival é o Goku.", "Usa a técnica Galick Gun."] },
    { nome: "Zoro", dificuldade: "Fácil", dicas: ["Usa o estilo de três espadas.", "Tem o cabelo verde.", "Seu senso de direção é terrível."] },
    { nome: "Ash Ketchum", dificuldade: "Fácil", dicas: ["Sua jornada começou na Cidade de Paleta.", "Deseja ser um Mestre Pokémon.", "Nunca envelhece."] },
    { nome: "Nezuko Kamado", dificuldade: "Fácil", dicas: ["É uma Oni que não come humanos.", "Usa um bambu na boca.", "Pode mudar de tamanho."] },
    { nome: "L", dificuldade: "Fácil", dicas: ["É o maior detetive do mundo.", "Adora comer doces.", "Senta de um jeito muito estranho."] },
    { nome: "Ichigo Kurosaki", dificuldade: "Fácil", dicas: ["É um Shinigami substituto.", "Sua espada se chama Zangetsu.", "Tem o cabelo alaranjado."] },
    { nome: "Edward Elric", dificuldade: "Fácil", dicas: ["É conhecido como o Alquimista de Aço.", "Perdeu um braço e uma perna.", "Odeia ser chamado de baixinho."] },
    { nome: "Kakashi Hatake", dificuldade: "Fácil", dicas: ["É conhecido como o Ninja Copiador.", "Sempre lê livros 'Icha Icha'.", "Foi o Sexto Hokage."] },
    { nome: "Gon Freecss", dificuldade: "Fácil", dicas: ["Usa uma vara de pescar no início.", "Busca encontrar seu pai, Ging.", "Sua técnica é o Jajanken."] },
    { nome: "Sailor Moon", dificuldade: "Fácil", dicas: ["Usa o poder da Lua.", "Seu nome real é Usagi Tsukino.", "Luta pelo amor e pela justiça."] },
    { nome: "Killua Zoldyck", dificuldade: "Fácil", dicas: ["Vem de uma família de assassinos.", "Usa ioiôs como armas.", "Tem poderes elétricos."] },
    { nome: "All Might", dificuldade: "Fácil", dicas: ["Era o Símbolo da Paz.", "Sua frase é 'Eu estou aqui!'.", "Sua forma verdadeira é muito magra."] },
    { nome: "Sakura Haruno", dificuldade: "Fácil", dicas: ["É uma ninja médica.", "Tem uma força bruta devastadora.", "Fez parte do Time 7."] },
    { nome: "Natsu Dragneel", dificuldade: "Fácil", dicas: ["É um Dragon Slayer do Fogo.", "Tem um gato azul chamado Happy.", "Faz parte da guilda Fairy Tail."] },
    { nome: "Bulma", dificuldade: "Fácil", dicas: ["É uma cientista genial.", "Inventou o Radar do Dragão.", "Esposa do Vegeta."] },
    { nome: "Sasuke Uchiha", dificuldade: "Fácil", dicas: ["Busca vingança contra o irmão.", "Usa o Chidori.", "Possui o Sharingan."] },
    { nome: "Gaara", dificuldade: "Fácil", dicas: ["Carrega uma cabaça de areia.", "Tem a palavra 'Amor' tatuada na testa.", "Foi o Quinto Kazekage."] },
    { nome: "Meliodas", dificuldade: "Fácil", dicas: ["Líder dos Sete Pecados Capitais.", "Carrega o pecado da Ira.", "Dono da taverna Chapéu de Porco."] },
    { nome: "Deku", dificuldade: "Fácil", dicas: ["Nasceu sem poderes (Individualidade).", "Recebeu o One For All.", "Escreve tudo em cadernos de análise."] },
    { nome: "Todoroki", dificuldade: "Fácil", dicas: ["Usa gelo e fogo.", "Tem uma queimadura no rosto.", "Filho do herói Endeavor."] },
    { nome: "Hinata Hyuga", dificuldade: "Fácil", dicas: ["Possui o Byakugan.", "Sempre foi apaixonada pelo Naruto.", "Mestra do Punho Gentil."] },

    // --- MÉDIOS (CONHECIMENTO INTERMEDIÁRIO) ---
    { nome: "Itachi Uchiha", dificuldade: "Média", dicas: ["Massacrou seu próprio clã.", "Entrou para a Akatsuki.", "Mestre em Genjutsu."] },
    { nome: "Light Yagami", dificuldade: "Média", dicas: ["Encontrou o Death Note.", "Seu objetivo é limpar o mundo.", "É conhecido como Kira."] },
    { nome: "Hisoka", dificuldade: "Média", dicas: ["Usa cartas de baralho como armas.", "Sua técnica é a Bungee Gum.", "Tem visual de bobo da corte."] },
    { nome: "Mikasa Ackerman", dificuldade: "Média", dicas: ["Sempre usa um cachecol vermelho.", "Extremamente protetora com o Eren.", "Uma das melhores do Esquadrão de Reconhecimento."] },
    { nome: "Roy Mustang", dificuldade: "Média", dicas: ["É o Alquimista das Chamas.", "Usa luvas especiais que geram faíscas.", "Quer se tornar o Marechal."] },
    { nome: "Jiraiya", dificuldade: "Média", dicas: ["É um dos Três Sannins Lendários.", "Conhecido como o Ero-Sennin.", "Autor dos livros Icha Icha."] },
    { nome: "Erza Scarlet", dificuldade: "Média", dicas: ["Sua magia é de reequipar armaduras.", "É conhecida como Titânia.", "Ama bolo de morango."] },
    { nome: "Bakugo", dificuldade: "Média", dicas: ["Sua individualidade é explosão.", "Tem um temperamento agressivo.", "Rival de infância do Deku."] },
    { nome: "Ban", dificuldade: "Média", dicas: ["É imortal.", "Carrega o pecado da Ganância.", "Ama a fada Elaine."] },
    { nome: "InuYasha", dificuldade: "Média", dicas: ["É um meio-youkai cachorro.", "Sua espada se chama Tessaiga.", "Usa uma túnica vermelha de rato de fogo."] },
    { nome: "Rimuru Tempest", dificuldade: "Média", dicas: ["Reencarnou como um Slime.", "Líder da Federação de Jura Tempest.", "Pode absorver qualquer habilidade."] },
    { nome: "Kurapika", dificuldade: "Média", dicas: ["Busca recuperar os olhos escarlates.", "Usa correntes em combate.", "Único sobrevivente do clã Kurta."] },
    { nome: "Alphonse Elric", dificuldade: "Média", dicas: ["Sua alma está presa em uma armadura.", "É o irmão mais novo do Edward.", "Dócil e adora gatos."] },
    { nome: "Gintoki Sakata", dificuldade: "Média", dicas: ["Luta com uma espada de madeira.", "Adora leite de morango.", "É o dono da Yorozuya."] },
    { nome: "Aizen", dificuldade: "Média", dicas: ["Liderou os Arrancars.", "Sua espada cria ilusões perfeitas.", "Foi Capitão da 5ª Divisão."] },
    { nome: "Yusuke Urameshi", dificuldade: "Média", dicas: ["É um Detetive Espiritual.", "Sua técnica é o Leigun.", "Ficou famoso no Torneio das Trevas."] },
    { nome: "Ryuuk", dificuldade: "Média", dicas: ["É um Shinigami que ama maçãs.", "Deixou o Death Note cair na Terra.", "Diz que humanos são interessantes."] },
    { nome: "Sebastian Michaelis", dificuldade: "Média", dicas: ["É um mordomo demônio.", "Serve a Ciel Phantomhive.", "Diz: 'Sou apenas um mordomo e tanto'."] },
    { nome: "Yuno Gasai", dificuldade: "Média", dicas: ["É a rainha das Yanderes.", "Seu diário prevê o futuro do seu amado.", "Participa de um jogo de sobrevivência."] },
    { nome: "Lucy Heartfilia", dificuldade: "Média", dicas: ["É uma Maga Espiritual.", "Usa chaves douradas.", "Deseja escrever um romance."] },
    { nome: "Trafalgar Law", dificuldade: "Média", dicas: ["É o Cirurgião da Morte.", "Possui a Ope Ope no Mi.", "Pode criar uma 'Room'."] },
    { nome: "Roronoa Zoro", dificuldade: "Média", dicas: ["Foi o primeiro a entrar no bando do Chapéu de Palha.", "Usa o estilo Santoryu.", "Quer ser o maior espadachim do mundo."] },
    { nome: "Hiei", dificuldade: "Média", dicas: ["Possui o terceiro olho (Jagan).", "Usa as Chamas Negras do Inferno.", "Irmão da Yukina."] },
    { nome: "Meruem", dificuldade: "Média", dicas: ["É o Rei das Formigas Quimera.", "Adora jogar Gungi.", "Nasceu para ser o topo da evolução."] },
    { nome: "Kagome", dificuldade: "Média", dicas: ["Reencarnação da sacerdotisa Kikyo.", "Vem do Japão moderno através de um poço.", "Pode purificar a Joia de Quatro Almas."] },
    { nome: "Brook", dificuldade: "Média", dicas: ["É um esqueleto músico.", "Comeu a fruta da ressurreição.", "Sua risada é 'Yohohoho'."] },
    { nome: "Minato Namikaze", dificuldade: "Média", dicas: ["Conhecido como o Relâmpago Amarelo.", "Foi o Quarto Hokage.", "Pai do Naruto."] },
    { nome: "Boa Hancock", dificuldade: "Média", dicas: ["É a Imperatriz de Amazon Lily.", "Possui a Mero Mero no Mi.", "Apaixonada pelo Luffy."] },
    { nome: "Shikamaru Nara", dificuldade: "Média", dicas: ["Diz que tudo é um 'saco'.", "Usa sombras para lutar.", "Possui um QI acima de 200."] },
    { nome: "Mugen", dificuldade: "Média", dicas: ["Estilo de luta baseado em breakdance.", "Um dos protagonistas de Samurai Champloo.", "Tem um temperamento selvagem."] },

    // --- DIFÍCEIS (SÓ PARA OTAKUS RAIZ) ---
    { nome: "Makima", dificuldade: "Difícil", dicas: ["É o Demônio do Controle.", "Trabalha na Segurança Pública.", "Tem olhos com círculos amarelos."] },
    { nome: "Denji", dificuldade: "Difícil", dicas: ["Fez um contrato com o Pochita.", "Transforma-se no Homem-Motosserra.", "Seu sonho era apenas comer torrada com geleia."] },
    { nome: "Griffith", dificuldade: "Difícil", dicas: ["Líder do Bando do Falcão.", "Sacrificou seus amigos no Eclipse.", "Tornou-se Femto."] },
    { nome: "Guts", dificuldade: "Difícil", dicas: ["Conhecido como o Espadachim Negro.", "Carrega a espada 'Dragon Slayer'.", "Usa a armadura Berserker."] },
    { nome: "Jotaro Kujo", dificuldade: "Difícil", dicas: ["Seu Stand é o Star Platinum.", "Diz constantemente 'Yare Yare Daze'.", "Lutou contra o Dio no Egito."] },
    { nome: "Dio Brando", dificuldade: "Difícil", dicas: ["É um vampiro imortal.", "Seu Stand é o The World.", "Grita 'Muda Muda Muda'."] },
    { nome: "Lelouch vi Britannia", dificuldade: "Difícil", dicas: ["Possui o poder do Geass.", "Lidera a Ordem dos Cavaleiros Negros.", "Usa o codinome Zero."] },
    { nome: "Spike Spiegel", dificuldade: "Difícil", dicas: ["Caçador de recompensas espacial.", "Pilotava a nave Bebop.", "Mestre em Jeet Kune Do."] },
    { nome: "Alucard", dificuldade: "Difícil", dicas: ["É o vampiro mais poderoso.", "Trabalha para a organização Hellsing.", "Usa duas pistolas: Casull e Jackal."] },
    { nome: "Shinji Ikari", dificuldade: "Difícil", dicas: ["Pilota a Unidade EVA-01.", "Tem sérios traumas psicológicos.", "Sua frase é 'Eu não devo fugir'."] },
    { nome: "Rei Ayanami", dificuldade: "Difícil", dicas: ["Pilota a Unidade EVA-00.", "É um clone da mãe do Shinji.", "Extremamente inexpressiva."] },
    { nome: "Vash Stampede", dificuldade: "Difícil", dicas: ["Conhecido como o Furacão Humano.", "Tem uma recompensa enorme por sua cabeça.", "É um pacifista que usa uma arma."] },
    { nome: "Sesshomaru", dificuldade: "Difícil", dicas: ["Irmão mais velho do InuYasha.", "Youkai puro e poderoso.", "Tem uma marca de lua na testa."] },
    { nome: "Gilgamesh", dificuldade: "Difícil", dicas: ["O Rei dos Heróis.", "Possui o Portão da Babilônia.", "Chama todos de 'mestiços'."] },
    { nome: "Yuji Itadori", dificuldade: "Difícil", dicas: ["Engoliu um dedo amaldiçoado.", "Possui grande força física natural.", "Hospedeiro do Sukuna."] },
    { nome: "Sukuna", dificuldade: "Difícil", dicas: ["É o Rei das Maldições.", "Possui quatro braços e dois rostos.", "Interessado no Megumi Fushiguro."] },
    { nome: "Thorfinn", dificuldade: "Difícil", dicas: ["Busca vingança contra Askeladd.", "Trabalhou como mercenário desde criança.", "Protagonista de Vinland Saga."] },
    { nome: "Mob", dificuldade: "Difícil", dicas: ["Explode quando chega a 100%.", "É um paranormal extremamente forte.", "Seu nome real é Shigeo Kageyama."] },
    { nome: "Reigen Arataka", dificuldade: "Difícil", dicas: ["Diz ser um mestre espiritual.", "Na verdade, é um vigarista profissional.", "Mestre do Mob."] },
    { nome: "Power", dificuldade: "Difícil", dicas: ["É o Demônio do Sangue.", "Tem chifres vermelhos.", "Odeia vegetais."] },
    { nome: "Aki Hayakawa", dificuldade: "Difícil", dicas: ["Tinha contrato com o Demônio da Raposa.", "Usa uma katana com pregos.", "Perdeu a família para o Demônio da Pistola."] },
    { nome: "Miroku", dificuldade: "Difícil", dicas: ["Monge com um buraco negro na mão.", "Sofre de uma maldição hereditária.", "É muito mulherengo."] },
    { nome: "Sango", dificuldade: "Difícil", dicas: ["É uma exterminadora de monstros.", "Usa um bumerangue gigante (Hiraikotsu).", "Tem um gato demônio chamado Kirara."] },
    { nome: "Saber", dificuldade: "Difícil", dicas: ["Sua identidade real é o Rei Arthur.", "Sua espada é a Excalibur.", "Participa da Guerra do Santo Graal."] },
    { nome: "Archer", dificuldade: "Difícil", dicas: ["Usa o Unlimited Blade Works.", "Veste roupas vermelhas.", "É a versão futura de um protagonista."] },
    { nome: "Giorno Giovanna", dificuldade: "Difícil", dicas: ["Filho do Dio no corpo do Jonathan.", "Seu Stand é o Gold Experience.", "Deseja ser um 'Gang-Star'."] },
    { nome: "Chrollo Lucilfer", dificuldade: "Difícil", dicas: ["Líder da Trupe Fantasma.", "Rouba habilidades de outros usuários de Nen.", "Usa um livro chamado 'Princípios do Caçador'."] },
    { nome: "Jin", dificuldade: "Difícil", dicas: ["Samurai ronin tradicional.", "Usa óculos e luta com precisão.", "Personagem de Samurai Champloo."] },
    { nome: "Tatsumaki", dificuldade: "Difícil", dicas: ["Conhecida como Tornado do Terror.", "A paranormal mais poderosa da Classe S.", "Parece uma criança mas é adulta."] },
    { nome: "Genos", dificuldade: "Difícil", dicas: ["Ciborgue em busca de justiça.", "Discípulo do Saitama.", "Conhecido como Ciborgue Demoníaco."] },
    { nome: "Casca", dificuldade: "Difícil", dicas: ["Guerreira habilidosa do Bando do Falcão.", "Perdeu a memória após o Eclipse.", "Amada pelo Guts."] },
    { nome: "Asuka Langley", dificuldade: "Difícil", dicas: ["Pilota a Unidade EVA-02.", "É alemã e muito orgulhosa.", "Grita 'Anta Baka?'."] },
    { nome: "Luffy G5", dificuldade: "Difícil", dicas: ["Sua transformação representa a liberdade.", "Despertar da Hito Hito no Mi: Modelo Nika.", "Lutou contra Kaido com esse poder."] },
    { nome: "Kenpachi Zaraki", dificuldade: "Difícil", dicas: ["Capitão da 11ª divisão.", "Usa um tapa-olho que consome energia.", "Adora lutas sangrentas."] },
    { nome: "Grimmjow", dificuldade: "Difícil", dicas: ["É o 6º Espada.", "Sua forma liberada parece uma pantera.", "Rival do Ichigo."] },
    { nome: "Ulquiorra Cifer", dificuldade: "Difícil", dicas: ["Representa o aspecto do niilismo.", "É o 4º Espada.", "Possui uma segunda etapa de liberação."] },
    { nome: "Gajeel Redfox", dificuldade: "Difícil", dicas: ["É o Dragon Slayer de Ferro.", "Gosta de comer metal.", "Membro da guilda Fairy Tail."] },
    { nome: "Rin Tohsaka", dificuldade: "Difícil", dicas: ["Mestre na Guerra do Santo Graal.", "Usa magia de joias.", "Pertence a uma linhagem de magos prestigiada."] },
    { nome: "Megumi Fushiguro", dificuldade: "Difícil", dicas: ["Usa a técnica das Dez Sombras.", "Pode invocar o Mahoraga.", "É do clã Zenin."] },
    { nome: "Yusuke", dificuldade: "Difícil", dicas: ["Morreu no primeiro episódio salvando uma criança.", "Possui ascendência demoníaca (Mazoku).", "Seu melhor amigo é o Kuwabara."] }
];
