/**
 * Database de Quizzes - AckermanBot ⚔️
 * Total: 200 Perguntas com Opções
 */

module.exports = [
    // --- ATTACK ON TITAN (SHINGEKI NO KYOJIN) ---
    { pergunta: "Quem é o portador original do Titã Fundador na muralha?", opcoes: ["Eren", "Uri Reiss", "Rod Reiss", "Grisha"], correta: 1 },
    { pergunta: "Qual o nome da mãe do Eren?", opcoes: ["Carla", "Dina", "Mikasa", "Ymir"], correta: 0 },
    { pergunta: "Quem matou o Titã Colossal (Bertholdt)?", opcoes: ["Levi", "Eren", "Armin", "Mikasa"], correta: 2 },
    { pergunta: "Qual o sobrenome real da Historia?", opcoes: ["Ackerman", "Reiss", "Tybur", "Braun"], correta: 1 },
    { pergunta: "Quem é conhecido como 'O Soldado Mais Forte da Humanidade'?", opcoes: ["Erwin", "Eren", "Levi", "Mike"], correta: 2 },
    { pergunta: "Quantos anos os portadores de Titãs Originais vivem após herdar o poder?", opcoes: ["10 anos", "13 anos", "20 anos", "5 anos"], correta: 1 },
    { pergunta: "Qual o nome da muralha mais externa?", opcoes: ["Sina", "Rose", "Maria", "Nile"], correta: 2 },
    { pergunta: "De quem o Levi recebeu seu sobrenome?", opcoes: ["Kenny", "Kuchel", "Erwin", "Zeke"], correta: 1 },
    { pergunta: "Qual animal representa o Titã Bestial do Zeke?", opcoes: ["Leão", "Macaco", "Cavalo", "Touro"], correta: 1 },
    { pergunta: "Quem foi o 13º Comandante do Corpo de Entrega?", opcoes: ["Hange", "Levi", "Erwin", "Shadis"], correta: 2 },

    // --- ANIMES GERAIS ---
    { pergunta: "Quem é o autor de One Piece?", opcoes: ["Masashi Kishimoto", "Akira Toriyama", "Eiichiro Oda", "Tite Kubo"], correta: 2 },
    { pergunta: "Qual o nome do protagonista de Solo Leveling?", opcoes: ["Sung Jin-Woo", "Kirito", "Guts", "Tanjiro"], correta: 0 },
    { pergunta: "Em Naruto, quem foi o mestre do Jiraiya?", opcoes: ["Minato", "Orochimaru", "Hiruzen Sarutobi", "Tsunade"], correta: 2 },
    { pergunta: "Qual o nome da espada do Ichigo em Bleach?", opcoes: ["Muramasa", "Zangetsu", "Enma", "Kurama"], correta: 1 },
    { pergunta: "Quantas Esferas do Dragão existem em Dragon Ball?", opcoes: ["5", "6", "7", "8"], correta: 2 },
    { pergunta: "Qual a cor do cabelo do Trunks do futuro (original)?", opcoes: ["Azul", "Roxo", "Preto", "Amarelo"], correta: 1 },
    { pergunta: "Quem é o caçador de onis que usa a Respiração do Trovão?", opcoes: ["Tanjiro", "Inosuke", "Zenitsu", "Giyu"], correta: 2 },
    { pergunta: "Qual o nome do caderno de Death Note?", opcoes: ["Life Note", "Kill Note", "Death Note", "Shinigami Note"], correta: 2 },
    { pergunta: "Quem é o capitão do bando dos Chapéu de Palha?", opcoes: ["Zoro", "Luffy", "Sanji", "Usopp"], correta: 1 },
    { pergunta: "Qual o nome do soco mais forte do Saitama?", opcoes: ["Soco Normal", "Soco Sério", "Soco Divino", "Soco de Fogo"], correta: 1 },

    // --- CONHECIMENTOS GERAIS & CIÊNCIA ---
    { pergunta: "Qual é o maior planeta do Sistema Solar?", opcoes: ["Terra", "Marte", "Júpiter", "Saturno"], correta: 2 },
    { pergunta: "Qual elemento químico tem o símbolo 'O'?", opcoes: ["Ouro", "Oxigênio", "Ozônio", "Osmio"], correta: 1 },
    { pergunta: "Quem pintou a Mona Lisa?", opcoes: ["Picasso", "Van Gogh", "Leonardo da Vinci", "Dalí"], correta: 2 },
    { pergunta: "Qual a capital do Brasil?", opcoes: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correta: 2 },
    { pergunta: "Quantos continentes existem no mundo?", opcoes: ["5", "6", "7", "4"], correta: 1 },
    { pergunta: "Qual o metal cujo símbolo químico é Au?", opcoes: ["Prata", "Cobre", "Ouro", "Alumínio"], correta: 2 },
    { pergunta: "Quem inventou a lâmpada?", opcoes: ["Einstein", "Newton", "Thomas Edison", "Tesla"], correta: 2 },
    { pergunta: "Qual o osso mais longo do corpo humano?", opcoes: ["Fêmur", "Tíbia", "Rádio", "Costela"], correta: 0 },
    { pergunta: "Em que ano o homem pisou na Lua pela primeira vez?", opcoes: ["1965", "1969", "1972", "1959"], correta: 1 },
    { pergunta: "Qual o país mais populoso do mundo?", opcoes: ["Índia", "China", "EUA", "Rússia"], correta: 0 },

    // --- GEOGRAFIA ---
    { pergunta: "Em qual continente fica o Egito?", opcoes: ["Ásia", "Europa", "África", "América"], correta: 2 },
    { pergunta: "Qual é o maior oceano do mundo?", opcoes: ["Atlântico", "Índico", "Glacial", "Pacífico"], correta: 3 },
    { pergunta: "Qual a capital do Japão?", opcoes: ["Seul", "Pequim", "Tóquio", "Quioto"], correta: 2 },
    { pergunta: "Onde fica a Estátua da Liberdade?", opcoes: ["Londres", "Paris", "Nova York", "Roma"], correta: 2 },
    { pergunta: "Qual o maior país em extensão territorial?", opcoes: ["Canadá", "China", "Brasil", "Rússia"], correta: 3 },
    { pergunta: "Qual rio atravessa a cidade de Londres?", opcoes: ["Nilo", "Sena", "Tamisa", "Amazonas"], correta: 2 },
    { pergunta: "Qual a moeda oficial da União Europeia?", opcoes: ["Dólar", "Libra", "Euro", "Iene"], correta: 2 },
    { pergunta: "Em que país fica a Torre de Pisa?", opcoes: ["França", "Espanha", "Itália", "Grécia"], correta: 2 },
    { pergunta: "Qual deserto é o mais seco do mundo?", opcoes: ["Saara", "Atacama", "Gobi", "Kalahari"], correta: 1 },
    { pergunta: "Qual montanha é a mais alta do mundo?", opcoes: ["K2", "Everest", "Monte Fuji", "Aconcágua"], correta: 1 },

    // --- FUTEBOL ---
    { pergunta: "Qual seleção tem mais Copas do Mundo?", opcoes: ["Alemanha", "Itália", "Brasil", "Argentina"], correta: 2 },
    { pergunta: "Quem é o maior artilheiro da história das Copas?", opcoes: ["Pelé", "Ronaldo", "Miroslav Klose", "Messi"], correta: 2 },
    { pergunta: "Em qual time o Cristiano Ronaldo começou a carreira?", opcoes: ["Real Madrid", "Sporting", "Man. United", "Juventus"], correta: 1 },
    { pergunta: "Quem venceu a Copa do Mundo de 2022?", opcoes: ["França", "Brasil", "Argentina", "Croácia"], correta: 2 },
    { pergunta: "Qual estádio é conhecido como 'O Maracanã'?", opcoes: ["Estádio da Luz", "Jornalista Mário Filho", "Santiago Bernabéu", "Camp Nou"], correta: 1 },
    { pergunta: "Qual jogador tem mais Bolas de Ouro?", opcoes: ["Cristiano Ronaldo", "Ronaldinho", "Neymar", "Lionel Messi"], correta: 3 },
    { pergunta: "Quem era o capitão do Brasil no Penta em 2002?", opcoes: ["Cafu", "Ronaldo", "Lúcio", "Roberto Carlos"], correta: 0 },
    { pergunta: "Qual time venceu a Champions League 2023/24?", opcoes: ["Man. City", "Real Madrid", "Dortmund", "Bayern"], correta: 1 },
    { pergunta: "Quantos minutos dura uma partida oficial de futebol (sem acréscimos)?", opcoes: ["80", "90", "100", "45"], correta: 1 },
    { pergunta: "Qual a cor do cartão que expulsa o jogador?", opcoes: ["Amarelo", "Verde", "Azul", "Vermelho"], correta: 3 },

    // --- HISTÓRIA ---
    { pergunta: "Quem descobriu o Brasil?", opcoes: ["Vasco da Gama", "Cristóvão Colombo", "Pedro Álvares Cabral", "Américo Vespúcio"], correta: 2 },
    { pergunta: "Quem foi o primeiro presidente do Brasil?", opcoes: ["Getúlio Vargas", "Deodoro da Fonseca", "Dom Pedro II", "Juscelino Kubitschek"], correta: 1 },
    { pergunta: "Em que ano começou a Segunda Guerra Mundial?", opcoes: ["1914", "1939", "1945", "1918"], correta: 1 },
    { pergunta: "Quem foi o líder dos Direitos Civis nos EUA famoso pelo discurso 'I Have a Dream'?", opcoes: ["Malcolm X", "Barack Obama", "Martin Luther King Jr.", "Nelson Mandela"], correta: 2 },
    { pergunta: "Qual civilização construiu as pirâmides de Gizé?", opcoes: ["Maias", "Incas", "Gregos", "Egípcios"], correta: 3 },
    { pergunta: "Quem foi a primeira mulher a ganhar um Prêmio Nobel?", opcoes: ["Marie Curie", "Madre Teresa", "Dilma Rousseff", "Rosa Parks"], correta: 0 },
    { pergunta: "Qual era a capital da Alemanha Oriental?", opcoes: ["Bonn", "Munique", "Berlim Oriental", "Hamburgo"], correta: 2 },
    { pergunta: "Quem foi o imperador da França que tentou conquistar a Europa no século XIX?", opcoes: ["Luís XIV", "Napoleão Bonaparte", "Carlos Magno", "Robespierre"], correta: 1 },
    { pergunta: "Em que país ocorreu a Revolução Industrial?", opcoes: ["França", "EUA", "Inglaterra", "Alemanha"], correta: 2 },
    { pergunta: "Quem libertou os escravos no Brasil?", opcoes: ["Dom Pedro I", "Princesa Isabel", "Zumbi dos Palmares", "José do Patrocínio"], correta: 1 },

    // --- ENTRETENIMENTO & FILMES ---
    { pergunta: "Qual o filme de maior bilheteria de todos os tempos?", opcoes: ["Vingadores: Ultimato", "Avatar", "Titanic", "Star Wars"], correta: 1 },
    { pergunta: "Quem interpreta o Homem de Ferro nos cinemas?", opcoes: ["Chris Evans", "Robert Downey Jr.", "Tom Holland", "Mark Ruffalo"], correta: 1 },
    { pergunta: "Qual a cor da pele do Shrek?", opcoes: ["Azul", "Amarelo", "Verde", "Vermelho"], correta: 2 },
    { pergunta: "Como se chama o vilão principal de Harry Potter?", opcoes: ["Dumbledore", "Snape", "Voldemort", "Grindelwald"], correta: 2 },
    { pergunta: "Qual o nome da rede social criada por Mark Zuckerberg?", opcoes: ["Twitter", "Instagram", "Facebook", "TikTok"], correta: 2 },
    { pergunta: "Quem é o mestre do Kung Fu Panda?", opcoes: ["Mestre Shifu", "Mestre Oogway", "Mestre Tigresa", "Mestre Garça"], correta: 0 },
    { pergunta: "Qual a cor da pílula que o Neo toma em Matrix para ver a realidade?", opcoes: ["Azul", "Vermelha", "Verde", "Amarela"], correta: 1 },
    { pergunta: "Quem é o 'Rei do Pop'?", opcoes: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correta: 1 },
    { pergunta: "Qual super-herói é conhecido como 'O Cavaleiro das Trevas'?", opcoes: ["Super-Homem", "Homem-Aranha", "Batman", "Flash"], correta: 2 },
    { pergunta: "Qual o nome do robô azul de Star Wars?", opcoes: ["C-3PO", "R2-D2", "BB-8", "Wall-E"], correta: 1 },

    // --- COMIDAS & BEBIDAS ---
    { pergunta: "De onde é originária a Pizza?", opcoes: ["França", "Brasil", "Itália", "EUA"], correta: 2 },
    { pergunta: "Qual o ingrediente principal do chocolate?", opcoes: ["Açúcar", "Leite", "Cacau", "Baunilha"], correta: 2 },
    { pergunta: "Qual fruta é usada para fazer vinho?", opcoes: ["Maçã", "Pêra", "Uva", "Laranja"], correta: 2 },
    { pergunta: "Qual país é o maior produtor de café do mundo?", opcoes: ["Colômbia", "Vietnã", "Brasil", "Etiópia"], correta: 2 },
    { pergunta: "O que é o Sushi originalmente?", opcoes: ["Peixe Cru", "Arroz Temperado", "Alga Frita", "Macarrão"], correta: 1 },
    { pergunta: "Qual vitamina é abundante na laranja?", opcoes: ["Vitamina A", "Vitamina B", "Vitamina C", "Vitamina D"], correta: 2 },
    { pergunta: "Qual o principal ingrediente do Guacamole?", opcoes: ["Tomate", "Abacate", "Cebola", "Pimenta"], correta: 1 },
    { pergunta: "Como se chama a carne de porco curada e defumada?", opcoes: ["Bacon", "Salsicha", "Bife", "Frango"], correta: 0 },
    { pergunta: "Qual a bebida mais consumida no mundo depois da água?", opcoes: ["Café", "Cerveja", "Chá", "Refrigerante"], correta: 2 },
    { pergunta: "Qual o nome do açúcar encontrado no leite?", opcoes: ["Frutose", "Sacarose", "Lactose", "Glicose"], correta: 2 },

    // --- CORPO HUMANO & SAÚDE ---
    { pergunta: "Qual o maior órgão do corpo humano?", opcoes: ["Coração", "Fígado", "Pele", "Pulmão"], correta: 2 },
    { pergunta: "Quantos dentes tem um adulto normal?", opcoes: ["28", "30", "32", "36"], correta: 2 },
    { pergunta: "Qual o tipo sanguíneo conhecido como 'Doador Universal'?", opcoes: ["A+", "B-", "O-", "AB+"], correta: 2 },
    { pergunta: "Onde fica localizado o labirinto no corpo humano?", opcoes: ["Nariz", "Ouvido", "Cérebro", "Garganta"], correta: 1 },
    { pergunta: "Qual a função dos glóbulos vermelhos?", opcoes: ["Defesa", "Transportar Oxigênio", "Coagulação", "Digestão"], correta: 1 },
    { pergunta: "Quantos ossos tem o corpo humano adulto?", opcoes: ["150", "206", "300", "250"], correta: 1 },
    { pergunta: "Qual o principal músculo do sistema circulatório?", opcoes: ["Bíceps", "Coração", "Diafragma", "Língua"], correta: 1 },
    { pergunta: "O que o pâncreas produz?", opcoes: ["Adrenalina", "Insulina", "Saliva", "Suor"], correta: 1 },
    { pergunta: "Qual parte do olho dá a cor?", opcoes: ["Pupila", "Córnea", "Íris", "Retina"], correta: 2 },
    { pergunta: "Qual o tempo médio de gestação humana em semanas?", opcoes: ["30", "35", "40", "45"], correta: 2 },

    // --- TECNOLOGIA ---
    { pergunta: "Quem fundou a Microsoft?", opcoes: ["Steve Jobs", "Elon Musk", "Bill Gates", "Jeff Bezos"], correta: 2 },
    { pergunta: "O que significa a sigla 'WWW'?", opcoes: ["World Wide Web", "Web World Wide", "World Web Wide", "Work Wide Web"], correta: 0 },
    { pergunta: "Qual empresa fabrica o iPhone?", opcoes: ["Samsung", "Google", "Apple", "Microsoft"], correta: 2 },
    { pergunta: "Qual o sistema operacional mais usado em celulares?", opcoes: ["iOS", "Windows", "Android", "Linux"], correta: 2 },
    { pergunta: "O que significa 'CPU'?", opcoes: ["Central Process Unit", "Computer Personal Unit", "Control Power Unit", "Core Process Unit"], correta: 0 },
    { pergunta: "Em qual linguagem o Baileys (biblioteca deste bot) é escrito?", opcoes: ["Python", "Java", "JavaScript/TypeScript", "C++"], correta: 2 },
    { pergunta: "Qual o nome do bilionário dono da Tesla e do X (Twitter)?", opcoes: ["Mark Zuckerberg", "Elon Musk", "Jeff Bezos", "Larry Page"], correta: 1 },
    { pergunta: "O que é um 'Hardware'?", opcoes: ["Parte Física", "Parte Lógica", "Sistema Operacional", "Vírus"], correta: 0 },
    { pergunta: "Qual a principal função da memória RAM?", opcoes: ["Armazenar fotos", "Processamento rápido", "Resfriar o PC", "Ligar a tela"], correta: 1 },
    { pergunta: "O que é o 'Bluetooth'?", opcoes: ["Um cabo", "Conexão sem fio curta", "Um satélite", "Um tipo de tela"], correta: 1 },

    // --- ANIMAIS ---
    { pergunta: "Qual é o animal terrestre mais rápido?", opcoes: ["Leão", "Guepardo", "Cavalo", "Antílope"], correta: 1 },
    { pergunta: "Qual o maior mamífero do mundo?", opcoes: ["Elefante", "Baleia Azul", "Tubarão Baleia", "Girafa"], correta: 1 },
    { pergunta: "Onde os pinguins vivem naturalmente?", opcoes: ["Polo Norte", "Antártida", "Deserto", "Florestas"], correta: 1 },
    { pergunta: "Qual o único mamífero que voa?", opcoes: ["Pássaro", "Morcego", "Esquilo", "Pterodátilo"], correta: 1 },
    { pergunta: "Quantas patas tem uma aranha?", opcoes: ["6", "8", "10", "12"], correta: 1 },
    { pergunta: "Qual pássaro é famoso por repetir o que os humanos falam?", opcoes: ["Tucano", "Papagaio", "Arara", "Pomba"], correta: 1 },
    { pergunta: "Como se chama o coletivo de lobos?", opcoes: ["Alcateia", "Enxame", "Cardume", "Manada"], correta: 0 },
    { pergunta: "O que o urso polar come principalmente?", opcoes: ["Peixe", "Focas", "Pinguins", "Mel"], correta: 1 },
    { pergunta: "Qual animal é conhecido por mudar de cor?", opcoes: ["Lagarto", "Camaleão", "Cobra", "Sapo"], correta: 1 },
    { pergunta: "Qual o peixe mais temido dos oceanos?", opcoes: ["Golfinho", "Tubarão Branco", "Baleia", "Piranha"], correta: 1 },

    // --- ESPORTES DIVERSOS ---
    { pergunta: "Quantos jogadores tem um time de basquete em quadra?", opcoes: ["5", "6", "11", "7"], correta: 0 },
    { pergunta: "Qual a distância de uma Maratona?", opcoes: ["20km", "42,195km", "50km", "10km"], correta: 1 },
    { pergunta: "Em qual esporte se usa o termo 'Home Run'?", opcoes: ["Basquete", "Futebol", "Beisebol", "Tênis"], correta: 2 },
    { pergunta: "Quem é considerado o maior nadador de todos os tempos?", opcoes: ["Cesar Cielo", "Michael Phelps", "Usain Bolt", "Ian Thorpe"], correta: 1 },
    { pergunta: "Qual a cor da camisa do líder do Tour de France?", opcoes: ["Verde", "Branca", "Amarela", "Rosa"], correta: 2 },
    { pergunta: "Onde surgiram os Jogos Olímpicos?", opcoes: ["Roma", "Grécia", "Egito", "China"], correta: 1 },
    { pergunta: "Qual o nome da luta que usa apenas os pés e as mãos no Japão?", opcoes: ["Judô", "Caratê", "Boxe", "Muay Thai"], correta: 1 },
    { pergunta: "Qual a pontuação máxima de um 'Strike' no Boliche?", opcoes: ["10", "20", "30", "50"], correta: 2 },
    { pergunta: "Quem é o 'Rei do Futebol'?", opcoes: ["Messi", "Cristiano Ronaldo", "Zico", "Pelé"], correta: 3 },
    { pergunta: "Qual esporte o Tiger Woods joga?", opcoes: ["Tênis", "Golfe", "Poker", "F1"], correta: 1 },

    // --- GAMES ---
    { pergunta: "Qual o nome do protagonista de The Legend of Zelda?", opcoes: ["Zelda", "Ganon", "Link", "Mario"], correta: 2 },
    { pergunta: "Qual o jogo mais vendido da história?", opcoes: ["Minecraft", "GTA V", "Tetris", "Super Mario"], correta: 0 },
    { pergunta: "Qual o nome do encanador mais famoso dos games?", opcoes: ["Luigi", "Wario", "Mario", "Yoshi"], correta: 2 },
    { pergunta: "Em qual jogo você cai em uma ilha e precisa ser o último sobrevivente?", opcoes: ["FIFA", "Free Fire", "Minecraft", "God of War"], correta: 1 },
    { pergunta: "Qual o nome da empresa que criou o PlayStation?", opcoes: ["Nintendo", "Microsoft", "Sony", "Sega"], correta: 2 },
    { pergunta: "Qual o nome do protagonista de God of War?", opcoes: ["Zeus", "Kratos", "Ares", "Atreus"], correta: 1 },
    { pergunta: "Qual cor é o Sonic?", opcoes: ["Vermelho", "Verde", "Azul", "Amarelo"], correta: 2 },
    { pergunta: "No Minecraft, qual monstro explode?", opcoes: ["Zombie", "Skeleton", "Creeper", "Enderman"], correta: 2 },
    { pergunta: "Qual o nome do reino do Mario?", opcoes: ["Mushroom Kingdom", "Hyrule", "Kanto", "Azeroth"], correta: 0 },
    { pergunta: "Qual o nome da franquia onde você captura monstros em esferas?", opcoes: ["Digimon", "Yu-Gi-Oh", "Pokémon", "Monster Hunter"], correta: 2 },

    // --- CIÊNCIAS NATURAIS ---
    { pergunta: "Qual gás os humanos expiram?", opcoes: ["Oxigênio", "Gás Carbônico", "Nitrogênio", "Hidrogênio"], correta: 1 },
    { pergunta: "Qual a estrela mais próxima da Terra?", opcoes: ["Lua", "Marte", "Sol", "Estrela do Norte"], correta: 2 },
    { pergunta: "Quantos planetas existem no Sistema Solar?", opcoes: ["7", "8", "9", "10"], correta: 1 },
    { pergunta: "O que as abelhas coletam das flores?", opcoes: ["Mel", "Néctar", "Pólen", "Água"], correta: 1 },
    { pergunta: "Qual o estado físico do gelo?", opcoes: ["Líquido", "Gasoso", "Sólido", "Plasma"], correta: 2 },
    { pergunta: "Qual é a substância mais dura da natureza?", opcoes: ["Ouro", "Ferro", "Diamante", "Grafite"], correta: 2 },
    { pergunta: "O que o pulmão respira?", opcoes: ["Água", "Ar", "Fogo", "Terra"], correta: 1 },
    { pergunta: "Qual animal é um anfíbio?", opcoes: ["Cobra", "Sapo", "Peixe", "Jacaré"], correta: 1 },
    { pergunta: "A Terra gira em torno de quê?", opcoes: ["Da Lua", "Do Sol", "De Marte", "De Júpiter"], correta: 1 },
    { pergunta: "Qual a cor das folhas na maioria das plantas?", opcoes: ["Azul", "Vermelho", "Verde", "Amarelo"], correta: 2 },

    // --- CURIOSIDADES ---
    { pergunta: "Qual animal nunca dorme?", opcoes: ["Tubarão", "Golfinho", "Formiga", "Girafa"], correta: 2 },
    { pergunta: "Qual é a cor do sangue do polvo?", opcoes: ["Vermelho", "Verde", "Azul", "Incolor"], correta: 2 },
    { pergunta: "Onde fica o coração do camarão?", opcoes: ["Na barriga", "Na cabeça", "Nas patas", "No rabo"], correta: 1 },
    { pergunta: "Qual fruta tem as sementes do lado de fora?", opcoes: ["Maçã", "Uva", "Morango", "Melancia"], correta: 2 },
    { pergunta: "Quanto tempo dura um dia em Marte?", opcoes: ["12 horas", "24 horas", "24 horas e 37 min", "48 horas"], correta: 2 },
    { pergunta: "Qual o animal que morre após picar alguém?", opcoes: ["Mosquito", "Aranha", "Abelha", "Vespa"], correta: 2 },
    { pergunta: "Em que país surgiu o Halloween?", opcoes: ["EUA", "Irlanda", "México", "Inglaterra"], correta: 1 },
    { pergunta: "Qual o idioma oficial da Austrália?", opcoes: ["Australiano", "Espanhol", "Inglês", "Francês"], correta: 2 },
    { pergunta: "Quantos corações tem um polvo?", opcoes: ["1", "2", "3", "4"], correta: 2 },
    { pergunta: "Qual planeta é conhecido como o Planeta Vermelho?", opcoes: ["Vênus", "Marte", "Mercúrio", "Netuno"], correta: 1 },

    // --- LOGICA E MATEMATICA ---
    { pergunta: "Qual o resultado de 7 x 8?", opcoes: ["54", "56", "64", "48"], correta: 1 },
    { pergunta: "Quantos segundos tem um minuto?", opcoes: ["30", "60", "100", "120"], correta: 1 },
    { pergunta: "Qual o dobro de 15?", opcoes: ["20", "25", "30", "45"], correta: 2 },
    { pergunta: "Quantos lados tem um hexágono?", opcoes: ["5", "6", "7", "8"], correta: 1 },
    { pergunta: "Qual a raiz quadrada de 81?", opcoes: ["7", "8", "9", "10"], correta: 2 },
    { pergunta: "Qual o valor de Pi (aproximado)?", opcoes: ["3,10", "3,12", "3,14", "3,16"], correta: 2 },
    { pergunta: "Quanto é 100 dividido por 4?", opcoes: ["20", "25", "50", "10"], correta: 1 },
    { pergunta: "Quantos graus tem um ângulo reto?", opcoes: ["45", "90", "180", "360"], correta: 1 },
    { pergunta: "Qual o número romano para 10?", opcoes: ["V", "I", "X", "L"], correta: 2 },
    { pergunta: "Quanto é 2 + 2 x 0?", opcoes: ["0", "2", "4", "1"], correta: 1 },

    // --- MAIS ANIMES ---
    { pergunta: "Quem é o protagonista de Black Clover?", opcoes: ["Yuno", "Asta", "Noelle", "Yami"], correta: 1 },
    { pergunta: "Qual o nome da vila do Naruto?", opcoes: ["Areia", "Névoa", "Folha", "Nuvem"], correta: 2 },
    { pergunta: "Quem é o Deus da Destruição do Universo 7 em Dragon Ball?", opcoes: ["Goku", "Beerus", "Whis", "Freeza"], correta: 1 },
    { pergunta: "Qual o nome do protagonista de Hunter x Hunter?", opcoes: ["Killua", "Kurapika", "Gon", "Leorio"], correta: 2 },
    { pergunta: "Qual o poder principal em Jujutsu Kaisen?", opcoes: ["Ki", "Chakra", "Energia Amaldiçoada", "Nen"], correta: 2 },
    { pergunta: "Qual o nome do irmão do Edward Elric?", opcoes: ["Alphonse", "Roy", "Scar", "Envy"], correta: 0 },
    { pergunta: "Quem é a 'Criança do Demônio' em One Piece?", opcoes: ["Nami", "Robin", "Hancock", "Big Mom"], correta: 1 },
    { pergunta: "Qual o nome da forma final do Ichigo?", opcoes: ["Bankai", "Vasto Lorde", "Mugetsu", "Shikai"], correta: 2 },
    { pergunta: "Qual o objetivo do Ash Ketchum?", opcoes: ["Ser Hokage", "Ser Rei dos Piratas", "Ser Mestre Pokémon", "Ser um Shinigami"], correta: 2 },
    { pergunta: "Quem é o vilão de Berserk?", opcoes: ["Casca", "Griffith", "Zodd", "Skull Knight"], correta: 1 },

    // --- MISTO FINAL ---
    { pergunta: "Qual a capital da Alemanha?", opcoes: ["Munique", "Hamburgo", "Berlim", "Frankfurt"], correta: 2 },
    { pergunta: "Qual o maior animal voador?", opcoes: ["Águia", "Condor", "Albatroz", "Pterodátilo (extinto)"], correta: 2 },
    { pergunta: "Quem descobriu a gravidade?", opcoes: ["Einstein", "Galileu", "Newton", "Darwin"], correta: 2 },
    { pergunta: "Qual o nome da galáxia onde vivemos?", opcoes: ["Andrômeda", "Via Láctea", "Sombrero", "Triângulo"], correta: 1 },
    { pergunta: "Qual a maior ilha do mundo?", opcoes: ["Austrália", "Groenlândia", "Madagascar", "Japão"], correta: 1 },
    { pergunta: "Quem escreveu 'Romeu e Julieta'?", opcoes: ["Machado de Assis", "Shakespeare", "Dante", "Cervantes"], correta: 1 },
    { pergunta: "Qual o menor país do mundo?", opcoes: ["Mônaco", "Vaticano", "Malta", "San Marino"], correta: 1 },
    { pergunta: "Em qual cidade fica a Torre Eiffel?", opcoes: ["Londres", "Paris", "Madri", "Lisboa"], correta: 1 },
    { pergunta: "Qual a principal língua falada no México?", opcoes: ["Mexicano", "Inglês", "Espanhol", "Português"], correta: 2 },
    { pergunta: "Quem é o autor de Harry Potter?", opcoes: ["Tolkien", "George R.R. Martin", "J.K. Rowling", "Stephen King"], correta: 2 },
    { pergunta: "Qual a cor do cavalo branco de Napoleão?", opcoes: ["Preto", "Marrom", "Branco", "Cinza"], correta: 2 },
    { pergunta: "Qual o planeta mais quente?", opcoes: ["Mercúrio", "Vênus", "Marte", "Júpiter"], correta: 1 },
    { pergunta: "Quantos anos tem um século?", opcoes: ["10", "50", "100", "1000"], correta: 2 },
    { pergunta: "Qual o símbolo químico da água?", opcoes: ["CO2", "H2O", "NaCl", "O2"], correta: 1 },
    { pergunta: "Quem é o 'Pai da Aviação'?", opcoes: ["Irmãos Wright", "Santos Dumont", "Da Vinci", "Tesla"], correta: 1 },
    { pergunta: "Qual o oceano que banha o Brasil?", opcoes: ["Pacífico", "Índico", "Atlântico", "Ártico"], correta: 2 },
    { pergunta: "Qual a capital da Argentina?", opcoes: ["Santiago", "Lima", "Buenos Aires", "Montevidéu"], correta: 2 },
    { pergunta: "Quem foi o Rei do Rock?", opcoes: ["John Lennon", "Freddie Mercury", "Elvis Presley", "Mick Jagger"], correta: 2 },
    { pergunta: "Qual a maior floresta tropical do mundo?", opcoes: ["Congo", "Taiga", "Amazônica", "Mata Atlântica"], correta: 2 },
    { pergunta: "Qual a cor da lixeira de papel na reciclagem?", opcoes: ["Vermelho", "Verde", "Azul", "Amarelo"], correta: 2 }
];